name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f Dynatrace/requirements.txt ]; then pip install -r Dynatrace/requirements.txt; fi
      - name: Run pytest
        run: pytest
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Run Go tests
        run: go test ./...
